import { createClient } from '@supabase/supabase-js'

export const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
)

export interface AdminUser {
  uid: string
  email: string
  full_name: string
}

export interface CVData {
  cv_id: string;
  candidate_first_name: string;
  candidate_last_name: string;
  candidate_email: string;
  candidate_phone: string;
  candidate_address: string;
  candidate_profile_url: string;
  candidate_institution: string;
  candidate_current_stage: string;
  candidate_intl_experience_summary: string;
  candidate_work_experience_summary: string;
  candidate_notable_point: string;
  candidate_target_flag: number;
  candidate_target_reason: string;
  grand_total_awarded: number;
  grand_total_max: number;
  structure_visuals_awarded_sum: number;
  structure_visuals_max_sum: number;
  education_awarded_sum: number;
  education_max_sum: number;
  experience_awarded_sum: number;
  experience_max_sum: number;
  others_awarded_sum: number;
  others_max_sum: number;
  // Detailed criteria (example for Structure & Visuals)
  no_photo_desc: string;
  no_photo_points_awarded: number;
  no_photo_points_max: number;
  no_photo_feedback: string;
  english_cv_desc: string;
  english_cv_points_awarded: number;
  english_cv_points_max: number;
  english_cv_feedback: string;
  one_page_length_desc: string;
  one_page_length_points_awarded: number;
  one_page_length_points_max: number;
  one_page_length_feedback: string;
  single_column_layout_desc: string;
  single_column_layout_points_awarded: number;
  single_column_layout_points_max: number;
  single_column_layout_feedback: string;
  no_color_desc: string;
  no_color_points_awarded: number;
  no_color_points_max: number;
  no_color_feedback: string;
  readable_formatting_desc: string;
  readable_formatting_points_awarded: number;
  readable_formatting_points_max: number;
  readable_formatting_feedback: string;
  uniform_margins_desc: string;
  uniform_margins_points_awarded: number;
  uniform_margins_points_max: number;
  uniform_margins_feedback: string;
  three_section_structure_desc: string;
  three_section_structure_points_awarded: number;
  three_section_structure_points_max: number;
  three_section_structure_feedback: string;
  // Education
  education_completeness_desc: string;
  education_completeness_points_awarded: number;
  education_completeness_points_max: number;
  education_completeness_feedback: string;
  honors_tests_desc: string;
  honors_tests_points_awarded: number;
  honors_tests_points_max: number;
  honors_tests_feedback: string;
  relevant_courses_desc: string;
  relevant_courses_points_awarded: number;
  relevant_courses_points_max: number;
  relevant_courses_feedback: string;
  exchanges_double_degrees_desc: string;
  exchanges_double_degrees_points_awarded: number;
  exchanges_double_degrees_points_max: number;
  exchanges_double_degrees_feedback: string;
  // Experience
  reverse_chronological_desc: string;
  reverse_chronological_points_awarded: number;
  reverse_chronological_points_max: number;
  reverse_chronological_feedback: string;
  clear_titles_desc: string;
  clear_titles_points_awarded: number;
  clear_titles_points_max: number;
  clear_titles_feedback: string;
  experience_substance_desc: string;
  experience_substance_points_awarded: number;
  experience_substance_points_max: number;
  experience_substance_feedback: string;
  bullet_count_desc: string;
  bullet_count_points_awarded: number;
  bullet_count_points_max: number;
  bullet_count_feedback: string;
  action_verbs_desc: string;
  action_verbs_points_awarded: number;
  action_verbs_points_max: number;
  action_verbs_feedback: string;
  tangible_outcomes_desc: string;
  tangible_outcomes_points_awarded: number;
  tangible_outcomes_points_max: number;
  tangible_outcomes_feedback: string;
  use_of_numbers_desc: string;
  use_of_numbers_points_awarded: number;
  use_of_numbers_points_max: number;
  use_of_numbers_feedback: string;
  concision_clarity_desc: string;
  concision_clarity_points_awarded: number;
  concision_clarity_points_max: number;
  concision_clarity_feedback: string;
  // Others
  professional_email_desc: string;
  professional_email_points_awarded: number;
  professional_email_points_max: number;
  professional_email_feedback: string;
  phone_format_desc: string;
  phone_format_points_awarded: number;
  phone_format_points_max: number;
  phone_format_feedback: string;
  location_mobility_desc: string;
  location_mobility_points_awarded: number;
  location_mobility_points_max: number;
  location_mobility_feedback: string;
  professional_links_desc: string;
  professional_links_points_awarded: number;
  professional_links_points_max: number;
  professional_links_feedback: string;
  banned_header_desc: string;
  banned_header_points_awarded: number;
  banned_header_points_max: number;
  banned_header_feedback: string;
  skills_tools_desc: string;
  skills_tools_points_awarded: number;
  skills_tools_points_max: number;
  skills_tools_feedback: string;
  languages_desc: string;
  languages_points_awarded: number;
  languages_points_max: number;
  languages_feedback: string;
  certifications_desc: string;
  certifications_points_awarded: number;
  certifications_points_max: number;
  certifications_feedback: string;
  interests_desc: string;
  interests_points_awarded: number;
  interests_points_max: number;
  interests_feedback: string;
  summary_profile_desc: string;
  summary_profile_points_awarded: number;
  summary_profile_points_max: number;
  summary_profile_feedback: string;
  // Bonus bullets
  pass4_bullet_original: string;
  pass4_bullet_feedback: string;
  pass4_bullet_suggestion: string;
}
